// <auto-generated />
namespace WebApiNetFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class id_usuario4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(id_usuario4));
        
        string IMigrationMetadata.Id
        {
            get { return "201711130023207_id_usuario4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
